import React, { createContext, useContext, useState, type ReactNode } from 'react';

type Language = 'en' | 'hi' | 'mr' | 'pa';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations: Record<Language, Record<string, string>> = {
  en: {
    'landing.title': 'STEM Connect',
    'landing.subtitle': 'Embark on your scientific journey today!',
    'landing.selectRole': 'Select your role to continue',
    'role.student': 'Continue as Student',
    'role.teacher': 'Continue as Teacher',
    'common.loading': 'Loading...',
    'auth.login': 'Login to Your Account',
    'auth.signup': 'Create an Account',
    'auth.google': 'Continue with Google',
    'dashboard.welcome': 'Welcome',
    'dashboard.class': 'Class',
    'dashboard.school': 'School',
    'dashboard.recommended': 'Recommended for You 🎯',
    'dashboard.noClasses': 'No teachers from your school have signed up yet!',
    'dashboard.joinClass': 'Join Class',
    'dashboard.haveCode': 'Have a code from your teacher?',
    'dashboard.enterCode': 'Enter Code (e.g. MATH BY XYZ)',
    'dashboard.selfLearning': 'Self Learning Mode 🚀',
    'dashboard.startAdventure': 'Start Adventure',
    'teacher.dashboard': 'Teacher Dashboard 👨‍🏫',
    'teacher.noClasses': 'No Classes Found',
    'teacher.noClassesDesc': 'You have not generated any active classrooms yet.',
    'teacher.generateCode': 'Generate a Code',
    'teacher.classroomCode': 'Classroom Code',
    'teacher.enrolled': 'Enrolled Students',
    'teacher.noStudents': 'No students have joined using this code yet.',
    'teacher.unknown': 'Unknown',
    'teacher.level1': 'Level 1',
    'map.welcome': "Hi {name}! Welcome to your learning journey. Let's begin!",
    'map.friend': 'Friend',
    'map.clickAudio': '🔊 Click me to hear it out loud!',
    'profile.settings': 'Account Settings',
    'profile.student': 'Student',
    'profile.teacher': 'Teacher',
    'profile.points': 'Total Points',
    'profile.dashboard': 'My Dashboard',
    'profile.edit': 'Edit Profile Details',
    'profile.signout': 'Sign Out',
    'map.lvl.frac.title': 'Fractions',
    'map.lvl.frac.desc': 'Master Numerators',
    'map.lvl.eq.title': 'Equations',
    'map.lvl.eq.desc': 'Solve for X',
    'frac.m1.title': '1. The Basics',
    'frac.m1.desc': 'Learn what fractions are through Mother\'s rotis.',
    'frac.m1.reward': 'Reward: 200 PTS',
    'frac.m1.locked': 'Unlocked',
    'frac.m2.title': '2. Combining Parts',
    'frac.m2.desc': 'Can we add them together?',
    'frac.m2.reward': 'Reward: 200 PTS',
    'frac.m2.locked': 'Requires 200 PTS',
    'frac.m1.probVoice': 'Mother has just cooked 1 large, hot roti on the chulha. Her 2 hungry children are sitting right next to her, eagerly waiting to eat. She needs to divide the roti so that both siblings get an exactly equal share. How much of the roti will each child get?',
    'frac.m1.probUI': 'Mother has just cooked 1 large, hot roti on the chulha. Her 2 hungry children are sitting right next to her, eagerly waiting to eat. She needs to divide the roti so that both siblings get an exactly equal share. How much of the roti will each child get?',
    'frac.m1.err': 'Oops! Think about dividing 1 whole roti equally between 2 people. Try again!',
    'frac.m1.optA': 'A) 1/4 and 3/4',
    'frac.m1.optB': 'B) 1/2 and 1/2 (Two equal Halves)',
    'frac.m1.optC': 'C) 1/3 and 2/3',
    'frac.m1.step1': 'Step 1: Watch & Learn 📺',
    'frac.m1.vidSub': "Let's understand what Fractions are before we help Mother cook!",
    'frac.m1.btnPlay': "I've finished the video! Let's play.",
    'frac.m1.taskHead': "Mother's Roti Challenge 🫓",
    'frac.m1.succHead': 'Brilliant Work! 🎉',
    'frac.m1.succ': 'You correctly told Mother to give 1/2 (Half) of the roti to each child. Both siblings are happy!',
    'frac.m1.retMap': 'Return to Map',
    'frac.m2.probVoice': "You are cleaning up after lunch. You find exactly 1/2 of a roti on one plate, and exactly 1/2 of another roti on your brother's plate. If you take these two pieces and put them together on a single platter, what do you have mathematically?",
    'frac.m2.probUI': "You are cleaning up after lunch. You find exactly 1/2 of a roti on one plate, and exactly 1/2 of another roti on your brother's plate. If you take these two pieces and put them together on a single platter, what do you have mathematically?",
    'frac.m2.err': 'Not quite! If you stick two halves together, what do they make? Try again!',
    'frac.m2.optA': 'A) 1/4 (A quarter Roti)',
    'frac.m2.optB': 'B) 2 Whole Rotis',
    'frac.m2.optC': 'C) 1 (A Whole Roti)',
    'frac.m2.step1': 'Step 1: Adding Fractions 📺',
    'frac.m2.vidSub': "Let's see what happens when we glue parts back together!",
    'frac.m2.btnPlay': 'Finished! Show me the challenge.',
    'frac.m2.taskHead': 'Joining the Pieces 🧩',
    'frac.m2.succHead': 'Math Wizard! 🧙‍♂️',
    'frac.m2.succ': 'You correctly figured out that 1/2 + 1/2 = 1 Whole! Adding parts gives you the big picture.',
    'frac.m2.retMap': 'Complete Module (Return to World Map)',
    'onboarding.student.title': 'Student Profile Setup',
    'onboarding.student.step1.headline': 'Tell us about yourself!',
    'onboarding.student.namePlaceholder': 'What is your name?',
    'onboarding.student.agePlaceholder': 'Your Age',
    'onboarding.student.genderPlaceholder': 'Select Gender',
    'onboarding.student.gender.male': 'Male',
    'onboarding.student.gender.female': 'Female',
    'onboarding.student.gender.other': 'Other',
    'onboarding.student.next': 'Next Step',
    'onboarding.student.step2.headline': 'Find your School',
    'onboarding.student.step2.sub': 'Click below to find schools near your location automatically.',
    'onboarding.student.findNearby': 'Find Nearby Schools 📍',
    'onboarding.student.locating': 'Locating...',
    'onboarding.student.selectNearby': '-- Choose from nearby --',
    'onboarding.student.manualPrompt': 'Cannot find your school? Add it manually.',
    'onboarding.student.manualHeadline': 'Enter your school name manually.',
    'onboarding.student.manualPlaceholder': 'Enter School Name',
    'onboarding.student.backToLocation': 'Go back to Location search',
    'onboarding.student.skip': 'Skip',
    'onboarding.student.continue': 'Continue',
    'onboarding.student.step3.headline': 'Select your Class',
    'onboarding.student.classPlaceholder': 'Which class are you in?',
    'onboarding.student.class5': 'Class 5',
    'onboarding.student.class6': 'Class 6',
    'onboarding.student.class7': 'Class 7',
    'onboarding.student.finish': 'Finish & Start Learning 🚀',
    'onboarding.teacher.title': 'Teacher Setup',
    'onboarding.teacher.namePlaceholder': 'Full Name (e.g. Priya Sharma)',
    'onboarding.teacher.schoolPlaceholder': 'School Name',
    'onboarding.teacher.sub6': 'Class 6',
    'onboarding.teacher.sub7': 'Class 7',
    'onboarding.teacher.math': 'Math',
    'onboarding.teacher.science': 'Science',
    'onboarding.teacher.generate': 'Generate Subject Code',
    'onboarding.teacher.success': 'Your Classroom Code is Ready!',
    'onboarding.teacher.shareDesc': 'Share this exact code with your students. They will use it to enter your learning track!',
    'onboarding.teacher.goDashboard': 'Go to Dashboard',
  },
  hi: {
    'landing.title': 'स्टेम कनेक्ट',
    'landing.subtitle': 'आज ही अपनी वैज्ञानिक यात्रा शुरू करें!',
    'landing.selectRole': 'आगे बढ़ने के लिए अपनी भूमिका चुनें',
    'role.student': 'छात्र के रूप में जारी रखें',
    'role.teacher': 'शिक्षक के रूप में जारी रखें',
    'common.loading': 'लोड हो रहा है...',
    'auth.login': 'अपने खाते में प्रवेश करें',
    'auth.signup': 'खाता बनाएं',
    'auth.google': 'Google के साथ जारी रखें',
    'dashboard.welcome': 'स्वागत है',
    'dashboard.class': 'कक्षा',
    'dashboard.school': 'विद्यालय',
    'dashboard.recommended': 'आपके लिए अनुशंसित 🎯',
    'dashboard.noClasses': 'आपके स्कूल के किसी भी शिक्षक ने अभी तक कोड साझा नहीं किया है।',
    'dashboard.joinClass': 'कक्षा में जुड़ें',
    'dashboard.haveCode': 'आपके शिक्षक का कोड है?',
    'dashboard.enterCode': 'कोड दर्ज करें',
    'dashboard.selfLearning': 'स्व-शिक्षा विधा 🚀',
    'dashboard.startAdventure': 'यात्रा शुरू करें',
    'teacher.dashboard': 'शिक्षक डैशबोर्ड 👨‍🏫',
    'teacher.noClasses': 'कोई कक्षा नहीं मिली',
    'teacher.noClassesDesc': 'आपने अभी तक कोई सक्रिय कक्षा नहीं बनाई है।',
    'teacher.generateCode': 'कोड जनरेट करें',
    'teacher.classroomCode': 'कक्षा का कोड',
    'teacher.enrolled': 'नामित दर्ज छात्र',
    'teacher.noStudents': 'अभी तक किसी भी छात्र ने इस कोड का उपयोग करके प्रवेश नहीं लिया है।',
    'teacher.unknown': 'अज्ञात',
    'teacher.level1': 'स्तर 1',
    'map.welcome': "नमस्ते {name}! आपकी सीखने की यात्रा में आपका स्वागत है। चलिए शुरू करते हैं!",
    'map.friend': 'दोस्त',
    'map.clickAudio': '🔊 इसे सुनने के लिए मुझे क्लिक करें!',
    'profile.settings': 'खाता सेटिंग्स (Account Settings)',
    'profile.student': 'छात्र (Student)',
    'profile.teacher': 'शिक्षक (Teacher)',
    'profile.points': 'कुल अंक (Total Points)',
    'profile.dashboard': 'मेरा डैशबोर्ड (My Dashboard)',
    'profile.edit': 'प्रोफ़ाइल विवरण संपादित करें (Edit Detail)',
    'profile.signout': 'लॉग आउट (Sign Out)',
    'map.lvl.frac.title': 'भिन्न (Fractions)',
    'map.lvl.frac.desc': 'अंश सीखें (Master Numerators)',
    'map.lvl.eq.title': 'समीकरण (Equations)',
    'map.lvl.eq.desc': 'X का मान निकालें (Solve for X)',
    'frac.m1.title': '1. मूल बातें (The Basics)',
    'frac.m1.desc': 'माँ की रोटियों के माध्यम से जानें कि भिन्न क्या हैं (Learn what fractions are)',
    'frac.m1.reward': 'इनाम: 200 अंक (Reward: 200 PTS)',
    'frac.m1.locked': 'खुला हुआ (Unlocked)',
    'frac.m2.title': '2. टुकड़ों को मिलाना (Combining Parts)',
    'frac.m2.desc': 'क्या हम उन्हें एक साथ जोड़ सकते हैं? (Can we add them together?)',
    'frac.m2.reward': 'इनाम: 200 अंक (Reward: 200 PTS)',
    'frac.m2.locked': 'अनलॉक करने के लिए 200 अंक चाहिए (Requires 200 PTS)',
    'frac.m1.probVoice': 'माँ ने चूल्हे पर एक बड़ी रोटी बनाई है। उनके दो बच्चे बेसब्री से इंतज़ार कर रहे हैं। उन्हें रोटी को इस तरह बाँटना है कि दोनों को बिल्कुल बराबर हिस्सा मिले। प्रत्येक बच्चे को कितनी रोटी मिलेगी?',
    'frac.m1.probUI': 'माँ ने चूल्हे पर एक बड़ी रोटी बनाई है, उसे 2 बच्चों में बराबर बाँटना है। प्रत्येक बच्चे को कितनी रोटी मिलेगी? (Mother has just cooked 1 large, hot roti on the chulha... How much of the roti will each child get?)',
    'frac.m1.err': 'गलत! एक पूरी रोटी को 2 लोगों में बांटने के बारे में सोचें! (Oops! Think about dividing 1 whole roti equally between 2 people. Try again!)',
    'frac.m1.optA': 'A) 1/4 और 3/4 (1/4 and 3/4)',
    'frac.m1.optB': 'B) 1/2 और 1/2 (Two equal Halves)',
    'frac.m1.optC': 'C) 1/3 और 2/3 (1/3 and 2/3)',
    'frac.m1.step1': 'चरण 1: देखें और सीखें (Step 1: Watch & Learn 📺)',
    'frac.m1.vidSub': "माँ की मदद करने से पहले आइए समझें कि भिन्न क्या हैं! (Let's understand what Fractions are before we help Mother cook!)",
    'frac.m1.btnPlay': "वीडियो खत्म! चलो खेलते हैं (I've finished the video! Let's play.)",
    'frac.m1.taskHead': "माँ की रोटी चुनौती (Mother's Roti Challenge 🫓)",
    'frac.m1.succHead': 'शानदार काम! (Brilliant Work! 🎉)',
    'frac.m1.succ': 'आपने माँ को 1/2 देने के लिए सही कहा! (You correctly told Mother to give 1/2 (Half) of the roti to each child. Both siblings are happy!)',
    'frac.m1.retMap': 'मैप पर लौटें (Return to Map)',
    'frac.m2.probVoice': 'आप भोजन के बाद प्लेटें साफ कर रहे हैं। आपको एक प्लेट में 1/2 रोटी और दूसरी प्लेट में 1/2 रोटी मिलती है। यदि आप इन दोनों टुकड़ों को एक साथ रख दें, तो कुल कितनी रोटी बनेगी?',
    'frac.m2.probUI': 'आपको एक प्लेट में 1/2 रोटी और दूसरी प्लेट में 1/2 रोटी मिलती है। कुल कितनी रोटी बनेगी? (You find exactly 1/2 of a roti on one plate, and exactly 1/2 of another roti on your brother\'s plate... what do you have mathematically?)',
    'frac.m2.err': 'गलत! आधे और आधे को जोड़ने से क्या बनता है? (Not quite! If you stick two halves together, what do they make? Try again!)',
    'frac.m2.optA': 'A) 1/4 (A quarter Roti)',
    'frac.m2.optB': 'B) 2 (Whole Rotis)',
    'frac.m2.optC': 'C) 1 (A Whole Roti)',
    'frac.m2.step1': 'चरण 1: भिन्न जोड़ना (Step 1: Adding Fractions 📺)',
    'frac.m2.vidSub': "आइए देखें कि जब हम हिस्सों को वापस मिलाते हैं! (Let's see what happens when we glue parts back together!)",
    'frac.m2.btnPlay': 'वीडियो खत्म! मुझे चुनौती दिखाओ (Finished! Show me the challenge.)',
    'frac.m2.taskHead': 'टुकड़ों को मिलाना (Joining the Pieces 🧩)',
    'frac.m2.succHead': 'गणित के जादूगर! (Math Wizard! 🧙‍♂️)',
    'frac.m2.succ': 'आपने सही पता लगाया! 1/2 + 1/2 = 1 (You correctly figured out that 1/2 + 1/2 = 1 Whole! Adding parts gives you the big picture.)',
    'frac.m2.retMap': 'मॉड्यूल पूरा करें (Complete Module)',
    'onboarding.student.title': 'छात्र प्रोफाइल सेटअप (Student Profile Setup)',
    'onboarding.student.step1.headline': 'हमें अपने बारे में बताएं! (Tell us about yourself!)',
    'onboarding.student.namePlaceholder': 'आपका नाम क्या है? (What is your name?)',
    'onboarding.student.agePlaceholder': 'आपकी उम्र (Your Age)',
    'onboarding.student.genderPlaceholder': 'लिंग चुनें (Select Gender)',
    'onboarding.student.gender.male': 'पुरुष (Male)',
    'onboarding.student.gender.female': 'महिला (Female)',
    'onboarding.student.gender.other': 'अन्य (Other)',
    'onboarding.student.next': 'अगला कदम (Next Step)',
    'onboarding.student.step2.headline': 'अपना स्कूल चुनें (Find your School)',
    'onboarding.student.step2.sub': 'अपने आस-पास के स्कूलों को स्वचालित रूप से खोजने के लिए नीचे क्लिक करें। (Click below to find schools near you)',
    'onboarding.student.findNearby': 'आस-पास के स्कूल ढूंढें 📍 (Find Nearby Schools)',
    'onboarding.student.locating': 'ढूंढ रहे हैं... (Locating)',
    'onboarding.student.selectNearby': '-- पास के स्कूलों में से चुनें -- (-- Choose from nearby --)',
    'onboarding.student.manualPrompt': 'अपना स्कूल नहीं मिल रहा? इसे स्वयं जोड़ें। (Cannot find school? Add manually)',
    'onboarding.student.manualHeadline': 'अपने स्कूल का नाम स्वयं दर्ज करें। (Enter school name manually)',
    'onboarding.student.manualPlaceholder': 'स्कूल का नाम दर्ज करें (Enter School Name)',
    'onboarding.student.backToLocation': 'स्थान खोज पर वापस जाएँ (Back to Location search)',
    'onboarding.student.skip': 'छोड़ें (Skip)',
    'onboarding.student.continue': 'जारी रखें (Continue)',
    'onboarding.student.step3.headline': 'अपनी कक्षा चुनें (Select your Class)',
    'onboarding.student.classPlaceholder': 'अपनी कक्षा चुनें (Choose your Class)',
    'onboarding.student.class5': 'कक्षा 5 (Class 5)',
    'onboarding.student.class6': 'कक्षा 6 (Class 6)',
    'onboarding.student.class7': 'कक्षा 7 (Class 7)',
    'onboarding.student.finish': 'समाप्त करें और सीखना शुरू करें 🚀 (Finish & Start Learning)',
    'onboarding.teacher.title': 'शिक्षक सेटअप (Teacher Setup)',
    'onboarding.teacher.namePlaceholder': 'पूरा नाम (जैसे प्रिया शर्मा) (Full Name)',
    'onboarding.teacher.schoolPlaceholder': 'स्कूल का नाम (School Name)',
    'onboarding.teacher.sub6': 'कक्षा 6 (Class 6)',
    'onboarding.teacher.sub7': 'कक्षा 7 (Class 7)',
    'onboarding.teacher.math': 'गणित (Math)',
    'onboarding.teacher.science': 'विज्ञान (Science)',
    'onboarding.teacher.generate': 'विषय कोड जनरेट करें (Generate Code)',
    'onboarding.teacher.success': 'आपका क्लासरूम कोड तैयार है! (Code Ready!)',
    'onboarding.teacher.shareDesc': 'यह कोड अपने छात्रों के साथ साझा करें। (Share this code with students)',
    'onboarding.teacher.goDashboard': 'डैशबोर्ड पर जाएँ (Go to Dashboard)',
  },
  mr: {
    'landing.title': 'स्टेम कनेक्ट',
    'landing.subtitle': 'आजच तुमचा वैज्ञानिक प्रवास सुरू करा!',
    'landing.selectRole': 'पुढे जाण्यासाठी तुमची भूमिका निवडा',
    'role.student': 'विद्यार्थी म्हणून सुरू ठेवा',
    'role.teacher': 'शिक्षक म्हणून सुरू ठेवा',
    'common.loading': 'लोड होत आहे...',
    'auth.login': 'लॉगिन करा',
    'auth.signup': 'खाते तयार करा',
    'auth.google': 'Google सह सुरू ठेवा',
    'dashboard.welcome': 'स्वागत आहे',
    'dashboard.class': 'वर्ग',
    'dashboard.school': 'शाळा',
    'dashboard.recommended': 'तुमच्यासाठी शिफारस केलेले 🎯',
    'dashboard.noClasses': 'तुमच्या शाळेतील कोणत्याही शिक्षकाने अद्याप साइन अप केले नाही!',
    'dashboard.joinClass': 'वर्गात सामील व्हा',
    'dashboard.haveCode': 'तुमच्या शिक्षकाकडून कोड आहे का?',
    'dashboard.enterCode': 'कोड प्रविष्ट करा',
    'dashboard.selfLearning': 'स्वत: शिकण्याची मोड 🚀',
    'dashboard.startAdventure': 'प्रवास सुरू करा',
    'teacher.dashboard': 'शिक्षक डॅशबोर्ड 👨‍🏫',
    'teacher.noClasses': 'कोणतेही वर्ग आढळले नाहीत',
    'teacher.noClassesDesc': 'तुम्ही अद्याप कोणतेही सक्रिय वर्ग तयार केलेले नाहीत.',
    'teacher.generateCode': 'कोड तयार करा',
    'teacher.classroomCode': 'वर्ग कोड',
    'teacher.enrolled': 'नोंदणीकृत विद्यार्थी',
    'teacher.noStudents': 'या कोडचा वापर करून अद्याप कोणत्याही विद्यार्थ्याने प्रवेश घेतलेला नाही.',
    'teacher.unknown': 'अज्ञात',
    'teacher.level1': 'पातळी 1',
    'map.welcome': "नमस्कार {name}! तुमच्या शिकण्याच्या प्रवासात स्वागत आहे. चला सुरू करूया!",
    'map.friend': 'मित्रा',
    'map.clickAudio': '🔊 हे ऐकण्यासाठी माझ्यावर क्लिक करा!',
    'profile.settings': 'खाते सेटिंग्ज',
    'profile.student': 'विद्यार्थी',
    'profile.teacher': 'शिक्षक',
    'profile.points': 'एकूण गुण',
    'profile.dashboard': 'माझे डॅशबोर्ड',
    'profile.edit': 'प्रोफाइल संपादित करा',
    'profile.signout': 'साइन आउट करा',
    'map.lvl.frac.title': 'अपूर्णांक (Fractions)',
    'map.lvl.frac.desc': 'अंश शिका (Master Numerators)',
    'map.lvl.eq.title': 'समीकरणे (Equations)',
    'map.lvl.eq.desc': 'X चे मूल्य शोधा (Solve for X)',
    'frac.m1.title': '1. मूलभूत गोष्टी (The Basics)',
    'frac.m1.desc': 'भाकरीच्या माध्यमातून अपूर्णांक म्हणजे काय ते शिका (Learn what fractions are)',
    'frac.m1.reward': 'बक्षीस: 100 गुण',
    'frac.m1.locked': 'अनलॉक केले',
    'frac.m2.title': '2. भाग एकत्र करणे (Combining Parts)',
    'frac.m2.desc': 'आपण त्यांना एकत्र जोडू शकतो का? (Can we add them together?)',
    'frac.m2.reward': 'बक्षीस: 200 गुण (Reward: 200 PTS)',
    'frac.m2.locked': 'अनलॉक करण्यासाठी 200 गुण आवश्यक',
    'frac.m1.probVoice': 'Mother has just cooked 1 large, hot roti on the chulha. Her 2 hungry children are sitting right next to her, eagerly waiting to eat. She needs to divide the roti so that both siblings get an exactly equal share. How much of the roti will each child get?',
    'frac.m1.probUI': "आईने 1 मोठी पोळी बनवली आहे... (Mother has just cooked 1 large roti...)",
    'frac.m1.err': 'Oops! Think! Try again!',
    'frac.m1.optA': 'A) 1/4 and 3/4',
    'frac.m1.optB': 'B) 1/2 and 1/2 (Two equal Halves)',
    'frac.m1.optC': 'C) 1/3 and 2/3',
    'frac.m1.step1': 'Step 1: Watch & Learn 📺',
    'frac.m1.vidSub': "Let's understand Fractions!",
    'frac.m1.btnPlay': "Finished the video! Let's play.",
    'frac.m1.taskHead': "Mother's Challenge 🫓",
    'frac.m1.succHead': 'Brilliant! 🎉',
    'frac.m1.succ': 'You correctly told Mother to give 1/2...',
    'frac.m1.retMap': 'Return to Map',
    'frac.m2.probVoice': "You are cleaning up after lunch. You find exactly 1/2 of a roti on one plate, and exactly 1/2 of another roti on your brother's plate. If you take these two pieces and put them together on a single platter, what do you have mathematically?",
    'frac.m2.probUI': "तुम्हाला एका प्लेटमध्ये 1/2 आणि दुसऱ्या प्लेटवर 1/2 पोळी आढळते... (You find 1/2...)",
    'frac.m2.err': 'Not quite!',
    'frac.m2.optA': 'A) 1/4 (A quarter Roti)',
    'frac.m2.optB': 'B) 2 Whole Rotis',
    'frac.m2.optC': 'C) 1 (A Whole Roti)',
    'frac.m2.step1': 'Step 1: Adding Fractions 📺',
    'frac.m2.vidSub': "Let's see what happens!",
    'frac.m2.btnPlay': 'Finished! Show me!',
    'frac.m2.taskHead': 'Joining the Pieces 🧩',
    'frac.m2.succHead': 'Math Wizard! 🧙‍♂️',
    'frac.m2.succ': 'You correctly figured out 1/2 + 1/2 = 1',
    'frac.m2.retMap': 'Complete Module'
  },
  pa: {
    'landing.title': 'ਸਟੈਮ ਕਨੈਕਟ',
    'landing.subtitle': 'ਅੱਜ ਹੀ ਆਪਣੀ ਵਿਗਿਆਨਕ ਯਾਤਰਾ ਸ਼ੁਰੂ ਕਰੋ!',
    'landing.selectRole': 'ਅੱਗੇ ਵਧਣ ਲਈ ਆਪਣੀ ਭੂਮਿਕਾ ਚੁਣੋ',
    'role.student': 'ਵਿਦਿਆਰਥੀ ਵਜੋਂ ਜਾਰੀ ਰੱਖੋ',
    'role.teacher': 'ਅਧਿਆਪਕ ਵਜੋਂ ਜਾਰੀ ਰੱਖੋ',
    'common.loading': 'ਲੋਡ ਹੋ ਰਿਹਾ ਹੈ...',
    'auth.login': 'ਲਾਗਿਨ ਕਰੋ',
    'auth.signup': 'ਖਾਤਾ ਬਣਾਓ',
    'auth.google': 'ਗੂਗਲ ਨਾਲ ਜਾਰੀ ਰੱਖੋ',
    'dashboard.welcome': 'ਜੀ ਆਇਆਂ ਨੂੰ',
    'dashboard.class': 'ਜਮਾਤ',
    'dashboard.school': 'ਸਕੂਲ',
    'dashboard.recommended': 'ਤੁਹਾਡੇ ਲਈ ਸਿਫਾਰਸ਼ 🎯',
    'dashboard.noClasses': 'ਤੁਹਾਡੇ ਸਕੂਲ ਦੇ ਕਿਸੇ ਵੀ ਅਧਿਆਪਕ ਨੇ ਅਜੇ ਤੱਕ ਸਾਈਨ ਅੱਪ ਨਹੀਂ ਕੀਤਾ ਹੈ!',
    'dashboard.joinClass': 'ਕਲਾਸ ਵਿੱਚ ਸ਼ਾਮਲ ਹੋਵੋ',
    'dashboard.haveCode': 'ਕੀ ਤੁਹਾਡੇ ਕੋਲ ਅਧਿਆਪਕ ਦਾ ਕੋਡ ਹੈ?',
    'dashboard.enterCode': 'ਕੋਡ ਦਰਜ ਕਰੋ',
    'dashboard.selfLearning': 'ਸਵੈ-ਸਿੱਖਣ ਮੋਡ 🚀',
    'dashboard.startAdventure': 'ਸਫ਼ਰ ਸ਼ੁਰੂ ਕਰੋ',
    'teacher.dashboard': 'ਅਧਿਆਪਕ ਡੈਸ਼ਬੋਰਡ 👨‍🏫',
    'teacher.noClasses': 'ਕੋਈ ਕਲਾਸ ਨਹੀਂ ਮਿਲੀ',
    'teacher.noClassesDesc': 'ਤੁਸੀਂ ਅਜੇ ਤੱਕ ਕੋਈ ਸਰਗਰਮ ਕਲਾਸ ਨਹੀਂ ਬਣਾਈ ਹੈ।',
    'teacher.generateCode': 'ਕੋਡ ਬਣਾਓ',
    'teacher.classroomCode': 'ਕਲਾਸ ਕੋਡ',
    'teacher.enrolled': 'ਦਾਖਲ ਵਿਦਿਆਰਥੀ',
    'teacher.noStudents': 'ਅਜੇ ਤੱਕ ਕਿਸੇ ਵਿਦਿਆਰਥੀ ਨੇ ਇਸ ਕੋਡ ਦੀ ਵਰਤੋਂ ਕਰਕੇ ਦਾਖਲਾ ਨਹੀਂ ਲਿਆ ਹੈ।',
    'teacher.unknown': 'ਅਣਜਾਣ',
    'teacher.level1': 'ਲੈਵਲ 1',
    'map.welcome': "ਸਤਿ ਸ੍ਰੀ ਅਕਾਲ {name}! ਤੁਹਾਡੀ ਸਿੱਖਣ ਦੀ ਯਾਤਰਾ ਵਿੱਚ ਸੁਆਗਤ ਹੈ। ਆਓ ਸ਼ੁਰੂ ਕਰੀਏ!",
    'map.friend': 'ਦੋਸਤ',
    'map.clickAudio': '🔊 ਇਸ ਨੂੰ ਉੱਚੀ ਆਵਾਜ਼ ਵਿੱਚ ਸੁਣਨ ਲਈ ਮੈਨੂੰ ਕਲਿੱਕ ਕਰੋ!',
    'profile.settings': 'ਖਾਤਾ ਸੈਟਿੰਗਾਂ',
    'profile.student': 'ਵਿਦਿਆਰਥੀ',
    'profile.teacher': 'ਅਧਿਆਪਕ',
    'profile.points': 'ਕੁੱਲ ਅੰਕ',
    'profile.dashboard': 'ਮੇਰਾ ਡੈਸ਼ਬੋਰਡ',
    'profile.edit': 'ਪ੍ਰੋਫਾਈਲ ਦਾ ਸੰਪਾਦਨ ਕਰੋ',
    'profile.signout': 'ਸਾਈਨ ਆਊਟ ਕਰੋ',
    'map.lvl.frac.title': 'ਭਿੰਨਾਂ (Fractions)',
    'map.lvl.frac.desc': 'ਅੰਸ਼ ਸਿੱਖੋ (Master Numerators)',
    'map.lvl.eq.title': 'ਸਮੀਕਰਨਾਂ (Equations)',
    'map.lvl.eq.desc': 'X ਦਾ ਮੁੱਲ ਲੱਭੋ (Solve for X)',
    'frac.m1.title': '1. ਮੂਲ ਗੱਲਾਂ (The Basics)',
    'frac.m1.desc': 'ਰੋਟੀਆਂ ਰਾਹੀਂ ਭਿੰਨਾਂ ਬਾਰੇ ਜਾਣੋ (Learn what fractions are)',
    'frac.m1.reward': 'ਇਨਾਮ: 100 ਅੰਕ',
    'frac.m1.locked': 'ਖੋਲ੍ਹਿਆ ਹੋਇਆ',
    'frac.m2.title': '2. ਭਾਗਾਂ ਨੂੰ ਮਿਲਾਉਣਾ (Combining Parts)',
    'frac.m2.desc': 'ਕੀ ਅਸੀਂ ਉਨ੍ਹਾਂ ਨੂੰ ਇਕੱਠੇ ਜੋੜ ਸਕਦੇ ਹਾਂ? (Can we add them together?)',
    'frac.m2.reward': 'ਇਨਾਮ: 200 ਅੰਕ',
    'frac.m2.locked': 'ਅਨਲਾਕ ਕਰਨ ਲਈ 200 ਅੰਕ ਚਾਹੀਦੇ ਹਨ',
    'frac.m1.probVoice': 'Mother has just cooked 1 large, hot roti on the chulha. Her 2 hungry children are sitting right next to her, eagerly waiting to eat. She needs to divide the roti so that both siblings get an exactly equal share. How much of the roti will each child get?',
    'frac.m1.probUI': 'ਮਾਂ ਨੇ 1 ਵੱਡੀ ਰੋਟੀ ਬਣਾਈ ਹੈ... (Mother has just cooked 1 large roti...)',
    'frac.m1.err': 'Oops!',
    'frac.m1.optA': 'A) 1/4 and 3/4',
    'frac.m1.optB': 'B) 1/2 and 1/2 (Two equal Halves)',
    'frac.m1.optC': 'C) 1/3 and 2/3',
    'frac.m1.step1': 'Step 1: Watch & Learn 📺',
    'frac.m1.vidSub': "Let's understand Fractions!",
    'frac.m1.btnPlay': "Finished the video! Let's play.",
    'frac.m1.taskHead': "Mother's Challenge 🫓",
    'frac.m1.succHead': 'Brilliant! 🎉',
    'frac.m1.succ': 'You correctly told Mother to give 1/2...',
    'frac.m1.retMap': 'Return to Map',
    'frac.m2.probVoice': "You are cleaning up after lunch. You find exactly 1/2 of a roti on one plate, and exactly 1/2 of another roti on your brother's plate. If you take these two pieces and put them together on a single platter, what do you have mathematically?",
    'frac.m2.probUI': "ਤੁਹਾਨੂੰ ਇੱਕ ਪਲੇਟ ਵਿੱਚ 1/2 ਰੋਟੀ ਮਿਲਦੀ ਹੈ... (You find 1/2...)",
    'frac.m2.err': 'Not quite!',
    'frac.m2.optA': 'A) 1/4 (A quarter Roti)',
    'frac.m2.optB': 'B) 2 Whole Rotis',
    'frac.m2.optC': 'C) 1 (A Whole Roti)',
    'frac.m2.step1': 'Step 1: Adding Fractions 📺',
    'frac.m2.vidSub': "Let's see what happens!",
    'frac.m2.btnPlay': 'Finished!',
    'frac.m2.taskHead': 'Joining the Pieces 🧩',
    'frac.m2.succHead': 'Math Wizard! 🧙‍♂️',
    'frac.m2.succ': 'You correctly figured out 1/2 + 1/2 = 1',
    'frac.m2.retMap': 'Complete Module'
  }
};

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>(() => {
    return (localStorage.getItem('stem_pwa_lang') as Language) || 'en';
  });

  const handleSetLanguage = (lang: Language) => {
    setLanguage(lang);
    localStorage.setItem('stem_pwa_lang', lang);
  };

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage: handleSetLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
